version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: effortless_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3307:3306"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 WepAPI.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysql_data: