# Generated by Django 4.2.19 on 2025-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0002_account_journal_party_subscriber_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='account',
        ),
        migrations.RemoveField(
            model_name='party',
            name='expense_amount',
        ),
        migrations.RemoveField(
            model_name='party',
            name='expense_count',
        ),
        migrations.AlterField(
            model_name='account',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
