# Generated by Django 4.2.19 on 2025-03-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0003_remove_party_account_remove_party_expense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
