# Generated by Django 4.2.19 on 2025-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0004_tags_inexdetails_tag_transactions_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='date',
            field=models.DateField(),
        ),
    ]
