# Generated by Django 4.2.19 on 2025-03-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0004_account_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='outstanding',
        ),
        migrations.AddField(
            model_name='transactions',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
