# Generated by Django 4.2.19 on 2025-03-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0005_remove_transactions_outstanding_transactions_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
