# Generated by Django 4.2.19 on 2025-03-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0006_alter_transactions_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
