# Generated by Django 4.2.19 on 2025-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0007_alter_subscriber_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
