# Generated by Django 4.2.19 on 2025-03-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0008_alter_subscriber_alternative_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
