# Generated by Django 4.2.19 on 2025-03-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0011_account_bank_account_cash_journaldetails_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='journaldetails',
            name='amount',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Unreconciled', max_length=100),
        ),
    ]
