# Generated by Django 4.2.19 on 2025-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0012_remove_account_bank_remove_account_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journaldetails',
            name='transaction_type',
            field=models.CharField(default='journal', max_length=100),
        ),
    ]
