# Generated by Django 4.2.19 on 2025-03-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0013_alter_journaldetails_transaction_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subscribers',
        ),
    ]
