# Generated by Django 4.2.19 on 2025-03-26 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0014_rename_subscriber_subscribers'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('journal_number', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('prepared_by', models.CharField(max_length=100)),
                ('subscriber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
        ),
        migrations.AlterField(
            model_name='journaldetails',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.journalheaders'),
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
