# Generated by Django 4.2.19 on 2025-03-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0015_journalheaders_alter_journaldetails_journal_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JournalDetails',
            new_name='Journals',
        ),
        migrations.RenameField(
            model_name='journalheaders',
            old_name='subscriber_id',
            new_name='subscriber',
        ),
    ]
