# Generated by Django 4.2.19 on 2025-03-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0019_journals_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
