# Generated by Django 4.2.19 on 2025-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0020_alter_journals_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
