# Generated by Django 4.2.19 on 2025-03-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0022_alter_journals_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='date',
            new_name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='party',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='status',
        ),
        migrations.AddField(
            model_name='transactions',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='InExDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('reference_number', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(max_length=100)),
                ('status', models.CharField(default='Unreconciled', max_length=100)),
                ('posted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.account')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.party')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
        ),
    ]
