# Generated by Django 4.2.19 on 2025-03-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0023_rename_date_transactions_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inexdetails',
            name='status',
            field=models.CharField(default='unreconciled', max_length=100),
        ),
    ]
