# Generated by Django 4.2.19 on 2025-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0024_alter_inexdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='bach_id',
            field=models.CharField(default='000-000', max_length=100),
        ),
    ]
