# Generated by Django 4.2.19 on 2025-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0025_transactions_bach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='bach_id',
            field=models.CharField(blank=True, default='000-000', max_length=100, null=True),
        ),
    ]
