# Generated by Django 4.2.19 on 2025-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0026_alter_transactions_bach_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
