# Generated by Django 4.2.19 on 2025-03-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0027_journals_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='posted',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bach_id',
            field=models.CharField(blank=True, default='00000-00000', max_length=100, null=True),
        ),
    ]
