# Generated by Django 4.2.19 on 2025-04-14 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0028_remove_journals_posted_alter_transactions_bach_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalheaders',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='subscriber',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers'),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='bach_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SubscriberUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.account')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
            options={
                'db_table': 'Ahercode_account_details',
            },
        ),
    ]
