# Generated by Django 4.2.19 on 2025-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0029_journalheaders_posted_party_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inexdetails',
            name='selected_bank',
            field=models.IntegerField(default=0),
        ),
    ]
