# Generated by Django 5.1.7 on 2025-04-17 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0029_journalheaders_posted_party_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='CalendarEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ahercode.subscribers')),
            ],
        ),
    ]
