# Generated by Django 5.1.7 on 2025-04-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0030_subscribers_password_calendarevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
