# Generated by Django 4.2.19 on 2025-04-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ahercode', '0031_remove_account_count_accountdetails_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='count',
        ),
    ]
